Repository gardener/gardener-resource-manager, pull requests merged in 2020-11, with the labels that each got.

#81 Add health endpoint for a liveness probe
  charts/gardener-resource-manager/templates/deployment.yaml
  charts/gardener-resource-manager/templates/service.yaml
  charts/gardener-resource-manager/values.yaml
  cmd/gardener-resource-manager/app/app.go
Labels: area/ops-productivity, area/quality, area/robustness, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#85 Fix CRD health checks due to conversion errors
  pkg/controller/managedresources/health/health_checker.go
  pkg/health/health.go
  pkg/health/health_test.go
Labels: area/robustness, kind/bug, needs/changes, needs/ok-to-test, priority/normal, size/s

#86 move pkg/apis to api module
  .ci/pipeline_definitions
  .dockerignore
  Makefile
  api/go.mod
  api/go.sum
  api/resources/register.go
  api/resources/v1alpha1/doc.go
  api/resources/v1alpha1/helper/helper.go
  api/resources/v1alpha1/register.go
  api/resources/v1alpha1/types.go
  api/resources/v1alpha1/zz_generated.deepcopy.go
  cmd/gardener-resource-manager/app/app.go
  go.mod
  hack/update-codegen.sh
  pkg/api/resources/v1alpha1/helper/helper_test.go
  pkg/apis/resources
  pkg/controller/managedresources/controller.go
  pkg/controller/managedresources/filter.go
  pkg/controller/managedresources/filter_test.go
  pkg/controller/managedresources/health/health_controller.go
  pkg/controller/managedresources/objectindex.go
  pkg/controller/managedresources/objectindex_test.go
  pkg/controller/managedresources/secret_controller.go
  pkg/controller/managedresources/secret_controller_test.go
  pkg/controller/managedresources/sort.go
  pkg/controller/managedresources/sort_test.go
  pkg/health/health.go
  pkg/health/health_test.go
  pkg/manager/managedresources.go
  pkg/manager/resourcemanager_test.go
  pkg/mapper/to_mr.go
  pkg/mapper/to_mr_test.go
  pkg/mapper/to_secret.go
  pkg/mapper/to_secret_test.go
  pkg/predicate/class_changed.go
  pkg/predicate/class_changed_test.go
  pkg/predicate/condition_status.go
  pkg/predicate/condition_status_test.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/register.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/v1alpha1/doc.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/v1alpha1/helper/helper.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/v1alpha1/register.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/v1alpha1/types.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: area/quality, kind/api-change, kind/technical-debt, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#88 fix api module tag
  .ci/pipeline_definitions
Labels: area/quality, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#87 Use patch to add/remove finalizer
  pkg/controller/utils/utils.go
Labels: area/cost, kind/task, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#91 Add "SKIP_FETCH_TOOLS=1" to make test-cov
  Makefile
Labels: needs/ok-to-test, size/xs

#90 Conditions `lastUpdateTime` is no longer updated continuously
  api/resources/v1alpha1/helper/helper.go
  cmd/gardener-resource-manager/app/app.go
  example/20-managedresource.yaml
  go.mod
  go.sum
  pkg/api/resources/v1alpha1/helper/helper_test.go
  pkg/controller/managedresources/health/health_controller.go
  pkg/health/health.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/v1alpha1/helper/helper.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/utils.go
  vendor/github.com/gardener/gardener/hack/check-generate.sh
  vendor/github.com/gardener/gardener/hack/test-cover.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/constants/types_constants.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_shoot.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/options.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/scaling.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/types.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/utils/client.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/object.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/patch.go
  vendor/github.com/gardener/gardener/pkg/utils/labels.go
  vendor/github.com/gardener/gardener/pkg/utils/managedresources/managedresources.go
  vendor/github.com/onsi/gomega/gstruct/elements.go
  vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go
  vendor/github.com/onsi/gomega/gstruct/fields.go
  vendor/github.com/onsi/gomega/gstruct/ignore.go
  vendor/github.com/onsi/gomega/gstruct/keys.go
  vendor/github.com/onsi/gomega/gstruct/pointer.go
  vendor/github.com/onsi/gomega/gstruct/types.go
  vendor/modules.txt
Labels: area/robustness, area/scalability, kind/api-change, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m
