Repository gardener/gardener-resource-manager, pull requests merged in 2021-07, with the labels that each got.

#124 Upgrade to go 1.16
  Dockerfile
  api/go.sum
  go.mod
  go.sum
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m

#125 Use resources.gardener.cloud in annotations
  api/resources/v1alpha1/types.go
  pkg/controller/managedresource/merger_test.go
  vendor/github.com/gardener/gardener-resource-manager/api/resources/v1alpha1/types.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#128 Fix the --version flag
  Makefile
  cmd/gardener-resource-manager/app/app.go
  go.mod
  pkg/version/version.go
  vendor/k8s.io/component-base/version/verflag/verflag.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/s

#129 [release-v0.25] Automated cherry pick of #128: Fix the --version flag
  Makefile
  cmd/gardener-resource-manager/app/app.go
  go.mod
  pkg/version/version.go
  vendor/k8s.io/component-base/version/verflag/verflag.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/s
