Repository gardener/gardener-resource-manager, pull requests merged in 2021-02, with the labels that each got.

#108 accept existing loadbalancerIP
  pkg/controller/managedresource/merger.go
  pkg/controller/managedresource/merger_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#89 add origin annotation to resources created an behalf of a managed resource
  .gitignore
  cmd/gardener-resource-manager/app/app.go
  docs/concepts/managed-resource.md
  pkg/controller/managedresource/add.go
  pkg/controller/managedresource/merger.go
  pkg/controller/managedresource/merger_test.go
  pkg/controller/managedresource/reconciler.go
Labels: area/control-plane, kind/enhancement, merge/squash, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#106 Read service events during deletion
  .gitignore
  go.mod
  go.sum
  pkg/cmd/target.go
  pkg/controller/health/health_checker.go
  pkg/controller/health/reconciler.go
  pkg/controller/managedresource/reconciler.go
  pkg/health/health.go
  pkg/health/health_test.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/utils.go
  vendor/github.com/gardener/gardener/hack/.ci/component_descriptor
  vendor/github.com/gardener/gardener/hack/get-build-ld-flags.sh
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/clientset.go
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/types.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/finalizers.go
  vendor/github.com/gardener/gardener/pkg/controllerutils/pointers.go
  vendor/github.com/gardener/gardener/pkg/operation/common/utils.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/taskfn.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/kubernetes.go
  vendor/github.com/gardener/gardener/pkg/version/version.go
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/k8s.io/component-base/version/base.go
  vendor/k8s.io/component-base/version/def.bzl
  vendor/k8s.io/component-base/version/version.go
  vendor/modules.txt
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#110 Add snapshot.storage.k8s.io/v1beta1 to target scheme
  go.mod
  go.sum
  pkg/cmd/target.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#111 Prevent context deadlines exceedances
  pkg/cmd/target.go
  pkg/controller/health/reconciler.go
  pkg/controller/managedresource/reconciler.go
Labels: area/scalability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#112 Fix discovery rate limits
  cmd/gardener-resource-manager/main.go
  pkg/cmd/source.go
  pkg/cmd/target.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#116 [release-v0.21] Cherry-pick of #112: Fix discovery rate limits
  pkg/cmd/source.go
  pkg/cmd/target.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#115 [release-v0.21] Cherry-pick of #110: Add snapshot.storage.k8s.io/v1beta1 to target scheme
  go.mod
  go.sum
  pkg/cmd/target.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/v2/pkg/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: reviewed/lgtm, size/xs

#113 [release-v0.21] Cherry-pick of #103: Improve accuracy of CheckDaemonSet function
  pkg/health/health.go
  pkg/health/health_test.go
Labels: reviewed/lgtm, reviewed/ok-to-test, size/s

#114 [release-v0.21] Cherry-pick of #108: accept existing loadbalancerIP
  pkg/controller/managedresource/merger.go
  pkg/controller/managedresource/merger_test.go
Labels: needs/review, size/xs
